#include "CescFirmwareUploader.h"
#include "app/AppSettings.h"
#include "services/ConnectionManager.h"
#include "services/cesc/CescSession.h"
#include <QTimer>
#include <QtSerialPort/QSerialPortInfo>

CescFirmwareUploader::CescFirmwareUploader(ConnectionManager*c,AppSettings*a,CescSession*s,QObject*p):QObject(p),m_connection(c),m_settings(a),m_session(s),m_reconnect(new QTimer(this)){
 m_reconnect->setInterval(750); connect(m_reconnect,&QTimer::timeout,this,&CescFirmwareUploader::reconnect);
 connect(s->transactions(),&CescTransactionManager::completed,this,[this](quint16,quint8 v,quint8 c,Cesc::Status x,const QByteArray&b){response(v,c,x,b);});
 connect(s,&CescSession::stateChanged,this,[this](CescSession::State s){if((m_stage==Stage::WaitPort||m_stage==Stage::Connecting)&&s==CescSession::State::Ready){m_reconnect->stop();m_stage=Stage::Info;update(State::ReadingVersion,100,tr("Reading device information..."));m_session->transactions()->request(0,1,{});}});
}
bool CescFirmwareUploader::isBusy()const noexcept{return m_stage!=Stage::Idle;} CescFirmwareUploader::State CescFirmwareUploader::state()const noexcept{return m_state;} int CescFirmwareUploader::progress()const noexcept{return m_progress;} QString CescFirmwareUploader::statusText()const{return m_text;} QString CescFirmwareUploader::firmwareVersion()const{return m_version;}
void CescFirmwareUploader::update(State s,int p,const QString&t){m_state=s;m_progress=p;m_text=t;emit stateChanged(s,p,t);emit progressChanged(p,t);}
void CescFirmwareUploader::start(const QByteArray&i){if(isBusy())return;m_session->setEnabled(true);if(!m_session->isReady()){emit finished(false,tr("CESC HELLO is not ready"));return;}if(!(m_session->capabilities()&Cesc::FirmwareUpdate)){emit finished(false,tr("Firmware update is not supported"));return;}if(i.isEmpty()||i.size()>8000000){emit finished(false,tr("Invalid firmware size"));return;}m_image=i;m_crc=crc32(i);m_offset=0;m_oldSession=m_session->sessionId();m_connection->setFirmwareOperationActive(true);m_stage=Stage::Stop;update(State::Preparing,0,tr("Stopping telemetry..."));m_session->transactions()->request(3,3,{});}
void CescFirmwareUploader::begin(){m_stage=Stage::Begin;QByteArray b;Cesc::appendU32(b,m_image.size());Cesc::appendU32(b,m_crc);Cesc::appendU16(b,qMin<quint16>(1024,m_session->maximumPayload()-10));Cesc::appendU16(b,0);m_session->transactions()->request(1,0,b,30000,2);update(State::Preparing,0,tr("Erasing..."));}
void CescFirmwareUploader::write(){if(m_offset>=quint32(m_image.size())){finishImage();return;}quint16 n=qMin<quint32>(m_chunk,m_image.size()-m_offset);QByteArray b;Cesc::appendU32(b,m_updateId);Cesc::appendU32(b,m_offset);Cesc::appendU16(b,n);b+=m_image.mid(m_offset,n);m_stage=Stage::Write;m_session->transactions()->request(1,1,b,3000,2);}
void CescFirmwareUploader::finishImage(){m_stage=Stage::Finish;QByteArray b;Cesc::appendU32(b,m_updateId);m_session->transactions()->request(1,2,b,10000,2);update(State::Verifying,100,tr("Verifying..."));}
void CescFirmwareUploader::activate(){m_stage=Stage::Activate;QByteArray b;Cesc::appendU32(b,m_updateId);Cesc::appendU16(b,250);m_session->transactions()->request(1,3,b,3000,1);}
void CescFirmwareUploader::response(quint8 svc,quint8 cmd,Cesc::Status status,const QByteArray&b){if(!isBusy())return;if(status!=Cesc::Status::Ok){done(false,tr("Command failed: %1").arg(quint16(status)));return;}qsizetype p=0;if(m_stage==Stage::Stop&&svc==3&&cmd==3)begin();else if(m_stage==Stage::Begin&&svc==1&&cmd==0){quint32 next;if(!Cesc::readU32(b,p,m_updateId)||!Cesc::readU16(b,p,m_chunk)||!Cesc::readU32(b,p,next)||!m_chunk){done(false,tr("Malformed BEGIN response"));return;}m_offset=next;write();}else if(m_stage==Stage::Write&&svc==1&&cmd==1){quint32 next;if(!Cesc::readU32(b,p,next)||next<m_offset||next>quint32(m_image.size())){done(false,tr("Invalid nextExpectedOffset"));return;}m_offset=next;update(State::Uploading,int(100ULL*m_offset/m_image.size()),tr("Uploading..."));write();}else if(m_stage==Stage::Finish&&svc==1&&cmd==2){quint32 size,crc;if(!Cesc::readU32(b,p,size)||!Cesc::readU32(b,p,crc)||size!=quint32(m_image.size())||crc!=m_crc){done(false,tr("Verification mismatch"));return;}activate();}else if(m_stage==Stage::Activate&&svc==1&&cmd==3)recover();else if(m_stage==Stage::Info&&svc==0&&cmd==1){quint16 a,c,d,x,y,z;if(!Cesc::readU16(b,p,a)||!Cesc::readU16(b,p,c)||!Cesc::readU16(b,p,d)||!Cesc::readU16(b,p,x)||!Cesc::readU16(b,p,y)||!Cesc::readU16(b,p,z)||p+12>b.size()){done(false,tr("Malformed device info"));return;}p+=12;QString hw,build;if(!Cesc::readString(b,p,hw)||!Cesc::readString(b,p,build)||m_session->sessionId()==m_oldSession){done(false,tr("SessionId did not change after reboot"));return;}m_version=QStringLiteral("%1.%2.%3 · %4 · %5").arg(a).arg(c).arg(d).arg(hw,build);emit firmwareVersionChanged(m_version);done(true,tr("Firmware update completed"));}}
void CescFirmwareUploader::recover(){m_config=m_settings->serialConfig();QSerialPortInfo p(m_config.portName);m_serial=p.serialNumber();m_vid=p.hasVendorIdentifier()?p.vendorIdentifier():0;m_pid=p.hasProductIdentifier()?p.productIdentifier():0;m_attempt=0;m_stage=Stage::WaitPort;update(State::Rebooting,100,tr("Rebooting..."));QTimer::singleShot(500,this,[this]{if(m_stage==Stage::WaitPort){m_connection->disconnectTransportForFirmwareRecovery();m_reconnect->start();}});}
QString CescFirmwareUploader::findPort()const{QString old,id;int n=0;for(const auto&p:QSerialPortInfo::availablePorts()){if(!m_serial.isEmpty()&&p.serialNumber()==m_serial)return p.portName();if(m_vid&&m_pid&&p.hasVendorIdentifier()&&p.hasProductIdentifier()&&p.vendorIdentifier()==m_vid&&p.productIdentifier()==m_pid){id=p.portName();++n;}if(p.portName().compare(m_config.portName,Qt::CaseInsensitive)==0)old=p.portName();}return n==1?id:old;}
void CescFirmwareUploader::reconnect(){if(++m_attempt>40){done(false,tr("Reconnect timed out"));return;}if(m_stage==Stage::Connecting)return;QString p=findPort();if(p.isEmpty())return;m_config.portName=p;m_settings->setSerialConfig(m_config);m_stage=Stage::Connecting;m_connection->connectTransportForFirmwareRecovery(TransportType::SerialPort,m_config);}
void CescFirmwareUploader::cancel(){if(!isBusy())return;if(m_updateId){QByteArray b;Cesc::appendU32(b,m_updateId);m_session->transactions()->request(1,4,b,1000,0);}done(false,tr("Cancelled"));}
void CescFirmwareUploader::requestFirmwareVersion(){m_session->setEnabled(true);if(!m_session->isReady())return;m_stage=Stage::Info;m_connection->setFirmwareOperationActive(true);m_session->transactions()->request(0,1,{});}
void CescFirmwareUploader::done(bool ok,const QString&t){m_reconnect->stop();m_stage=Stage::Idle;m_image.clear();m_connection->setFirmwareOperationActive(false);update(ok?State::Completed:State::Failed,ok?100:m_progress,t);emit finished(ok,t);}
quint32 CescFirmwareUploader::crc32(const QByteArray&b){quint32 c=~0U;for(char x:b){c^=quint8(x);for(int i=0;i<8;++i)c=(c&1)?(c>>1)^0xedb88320U:c>>1;}return ~c;}
