#include "CescTelemetryClient.h"
#include "CescSession.h"
#include "services/ChannelDataHub.h"
#include <QDateTime>
#include <algorithm>
CescTelemetryClient::CescTelemetryClient(CescSession*s,ChannelDataHub*h,QObject*p):QObject(p),m_session(s),m_hub(h){
 connect(s,&CescSession::packetReceived,this,[this](const Cesc::Packet&p){if(p.messageType==Cesc::MessageType::Stream&&p.serviceId==3&&p.commandId==0x80)stream(p);});
 connect(s->transactions(),&CescTransactionManager::completed,this,[this](quint16,quint8 svc,quint8 cmd,Cesc::Status st,const QByteArray&b){if(svc!=3)return;if(st!=Cesc::Status::Ok){emit commandFailed(tr("Telemetry command failed: %1").arg(quint16(st)));return;}qsizetype p=0;if(cmd==0){quint16 total;quint8 n;if(!Cesc::readU16(b,p,total)||!Cesc::readU8(b,p,n))return;for(int i=0;i<n;++i){Channel c;quint8 t;if(!Cesc::readU16(b,p,c.id)||!Cesc::readU8(b,p,t)||!Cesc::readFloat32(b,p,c.scale)||!Cesc::readFloat32(b,p,c.offset)||!Cesc::readString(b,p,c.name)||!Cesc::readString(b,p,c.unit))return;c.type=Cesc::DataType(t);m_channels[c.id]=c;}emit channelsChanged();if(m_channels.size()<total&&!m_channels.isEmpty())enumerate(*std::max_element(m_channels.keyBegin(),m_channels.keyEnd())+1);}else if(cmd==1){quint16 id;quint32 period;quint8 samples,n;if(!Cesc::readU16(b,p,id)||!Cesc::readU32(b,p,period)||!Cesc::readU8(b,p,samples)||!Cesc::readU8(b,p,n))return;Stream x;for(int i=0;i<n;++i){quint16 c;if(!Cesc::readU16(b,p,c))return;x.channels<<c;}m_streams[id]=x;emit subscribed(id);}else if(cmd==2){/* removal follows request ownership at caller */}else if(cmd==3)m_streams.clear();});
 connect(s,&CescSession::sessionChanged,this,[this]{m_streams.clear();});
 connect(s,&CescSession::stateChanged,this,[this](CescSession::State state){
     if(state!=CescSession::State::Ready){m_streams.clear();m_timestampAligned=false;}
 });
}
void CescTelemetryClient::enumerate(quint16 first,quint8 count){QByteArray b;Cesc::appendU16(b,first);b.append(char(count));m_session->transactions()->request(3,0,b);}
void CescTelemetryClient::subscribe(const QList<quint16>&ids,quint32 period,quint8 samples){QByteArray b;Cesc::appendU32(b,period);b.append(char(samples));b.append(char(ids.size()));for(auto id:ids)Cesc::appendU16(b,id);m_session->transactions()->request(3,1,b);}
void CescTelemetryClient::unsubscribe(quint16 id){QByteArray b;Cesc::appendU16(b,id);m_session->transactions()->request(3,2,b);m_streams.remove(id);}void CescTelemetryClient::stopAll(){m_session->transactions()->request(3,3,{});}void CescTelemetryClient::getStreamStatus(quint16 id){QByteArray b;Cesc::appendU16(b,id);m_session->transactions()->request(3,4,b);}
quint16 CescTelemetryClient::activeStreamId()const noexcept{return m_streams.isEmpty()?0U:m_streams.cbegin().key();}
bool CescTelemetryClient::value(const QByteArray&b,qsizetype&p,Cesc::DataType t,double&v)const{quint8 u8;quint16 u16;quint32 u32;quint64 u64;float f;double d;switch(t){case Cesc::DataType::UInt8:if(!Cesc::readU8(b,p,u8))return false;v=u8;break;case Cesc::DataType::Int8:if(!Cesc::readU8(b,p,u8))return false;v=qint8(u8);break;case Cesc::DataType::UInt16:if(!Cesc::readU16(b,p,u16))return false;v=u16;break;case Cesc::DataType::Int16:if(!Cesc::readU16(b,p,u16))return false;v=qint16(u16);break;case Cesc::DataType::UInt32:if(!Cesc::readU32(b,p,u32))return false;v=u32;break;case Cesc::DataType::Int32:if(!Cesc::readU32(b,p,u32))return false;v=qint32(u32);break;case Cesc::DataType::UInt64:if(!Cesc::readU64(b,p,u64))return false;v=double(u64);break;case Cesc::DataType::Int64:if(!Cesc::readU64(b,p,u64))return false;v=double(qint64(u64));break;case Cesc::DataType::Float32:if(!Cesc::readFloat32(b,p,f))return false;v=f;break;case Cesc::DataType::Float64:if(!Cesc::readFloat64(b,p,d))return false;v=d;break;}return true;}
void CescTelemetryClient::stream(const Cesc::Packet&packet){qsizetype p=0;quint16 id;quint32 sampleSeq,period;quint64 first;quint8 samples,count;if(!Cesc::readU16(packet.payload,p,id)||!Cesc::readU32(packet.payload,p,sampleSeq)||!Cesc::readU64(packet.payload,p,first)||!Cesc::readU32(packet.payload,p,period)||!Cesc::readU8(packet.payload,p,samples)||!Cesc::readU8(packet.payload,p,count)||!m_streams.contains(id))return;auto&s=m_streams[id];if(count!=s.channels.size())return;if(!m_timestampAligned){m_deviceToHostOffsetUs=QDateTime::currentMSecsSinceEpoch()*1000-qint64(first);m_timestampAligned=true;}if(s.seen){quint16 expected=quint16(s.lastFrame+1);m_droppedFrames+=quint16(packet.sequence-expected);if(sampleSeq>s.nextSample)m_droppedSamples+=sampleSeq-s.nextSample;}s.seen=true;s.lastFrame=packet.sequence;s.nextSample=sampleSeq+samples;for(int i=0;i<samples;++i){ParsedMessage m;m.messageId=QStringLiteral("telemetry");m.displayName=tr("CESC telemetry");for(auto channelId:s.channels){if(!m_channels.contains(channelId))return;const auto&c=m_channels[channelId];double raw;if(!value(packet.payload,p,c.type,raw))return;m.fields.append({QString::number(c.id),c.name,raw*c.scale+c.offset,c.unit,ProtocolFieldRole::Value});}m_hub->publish(m_deviceToHostOffsetUs+qint64(first)+qint64(i)*period,QStringLiteral("cesc-v1"),{m});}emit streamGapDetected(m_droppedFrames,m_droppedSamples);}
